export default {
    name:'contact',
    title:'Contact',
    type:'document',
    fields:[
        {
            name:'firstname',
            title:'Fistname',
            type:'string'
        },
        {
            name:'lastname',
            title:'Lastname',
            type:'string'
        },
        {
            name:'gender',
            title:'Gender',
            type:'string'
        },
        {
            name:'phone',
            title:'Phone',
            type:'string'
        },
        {
            name:'email',
            title:'Email',
            type:'string'
        },
        {
            name:'message',
            title:'Message',
            type:'text'
        }
    ]
}